### ISSUE TITLE
Failed to execute 'matches' on 'Element'

### ISSUE THREAD

**Issue by ewgdg** [sissilab/obsidian-image-toolkit#35]
The plugin stops working recently after I upgraded it to version 0.5.1 . No response after clicking any image.
The console shows the following error message:
```
Uncaught DOMException: Failed to execute 'matches' on 'Element': 'img:not(a img)' is not a valid selector.
    at HTMLDivElement.<anonymous> (app://obsidian.md/app.js:1:133015)
    at HTMLDocument.s (app://obsidian.md/app.js:1:135596)
```

The corresponding lines of code:
```
        N(Element.prototype, "matchParent", (function(t, e) {
            if (this.matches(t))  // this line triggers the exception
                return this;
            if (this === e)
                return null;
            var n = this.parentElement;
            return n ? n.matchParent(t, e) : null
        }
        )),
```

My current obsidian version is v0.13.19 .

**Comment by ewgdg** [comment]
I tried reinstalled the plugin, the settings are the default ones.

**Comment by ewgdg** [comment]
I solved the problem by reinstalling with latest installer.
